Auto detect target when libmali runs without suffix (#1)
* Auto detect target when libmali runs without suffix

* Update libmali-wrapper

* Update sha256 for libmali-wrapper

* Update .SRCINFO

diff --git a/libmali-wrapper b/libmali-wrapper
--- a/libmali-wrapper
+++ b/libmali-wrapper
@@ -1,6 +1,7 @@
 #!/bin/bash
 # Multi-call wrapper for libmali by 7Ji based on https://aur.archlinux.org/cgit/aur.git/tree/libmali?h=linux-radxa-rkbsp5-git
 NAME=$(basename "$0")
+LIBMALI_PATH=/usr/lib/%MODEL%
 if ! [[ "${NAME}" =~ ^libmali* ]]; then
   echo "ERROR: Helper script called as $0 (basename ${NAME}), please call it as libmali*"
   exit 1
@@ -23,8 +24,20 @@ case "${SUFFIX}" in
   x11-wayland-gbm)
     TARGET=x11-wayland-gbm
     ;;
-  *)
+  [xX]*)
     TARGET=x11-gbm
+    ;;
+  *)
+    if [[ -d "${LIBMALI_PATH}/x11-wayland-gbm" ]]; then
+      TARGET=x11-wayland-gbm
+    elif [[ -d "${LIBMALI_PATH}/wayland-gbm" ]] && [ -n "$WAYLAND_DISPLAY" ]; then
+      TARGET=wayland-gbm
+    elif [[ -d "${LIBMALI_PATH}/x11-gbm" ]] && [ -n "$DISPLAY" ]; then
+      TARGET=x11-gbm
+    else
+      echo "ERROR: Failed to lookup libmali or display not initialized."
+      exit 1
+    fi
     ;;
 esac
 if [[ -z "$1" ]]; then
@@ -32,7 +45,7 @@ if [[ -z "$1" ]]; then
   exit 1
 fi
 
-LIBMALI=/usr/lib/"%MODEL%/${TARGET}"
+LIBMALI="${LIBMALI_PATH}/${TARGET}"
 if [[ ! -d "${LIBMALI}" ]]; then
   echo "ERROR: Failed to lookup libmali at '${LIBMALI}'"
   exit 1
